### ISSUE TITLE
Release version 1.24.0.1 ?

### ISSUE THREAD

**Issue by erikd** [haskell/cabal#4080]
The GCC in Debian recently enabled PIC/PIC by default, causing problems like https://ghc.haskell.org/trac/ghc/ticket/12759 . Fixing GHC is only part of the solution. The other part is in Cabal.

Would it be possible to release cabal 1.24.0.1 which includes https://github.com/haskell/cabal/commit/c993a0c6660aa10d8c79ed0cc4961c59acfc91c8 ?

**Comment by 23Skidoo** [comment]
1.24.1.0 will be released together with GHC 8.0.2. Actually, we can release it right now, since all blockers have been fixed.

**Comment by erikd** [comment]
@23Skidoo Your comment was from 9 hours ago, but its still not on Hackage. ETA?

**Comment by 23Skidoo** [comment]
I've sent an e-mail to @rthomas, so the tarballs should be out Real Soon Now. I'll build and upload binaries for various platforms during the weekend.

**Comment by erikd** [comment]
Thanks @23Skidoo. The rest is great but I really just need it on Hackage :).

**Comment by 23Skidoo** [comment]
@rthomas tells me that he'll do it during the weekend.

**Comment by rthomas** [comment]
Cabal 1.24.1.0 is now on Hackage.

**Comment by sjakobi** [comment]
The changelog for 1.24.1.0 lists a version 1.24.0.1, which I cannot find on Hackage. Maybe that entry could be removed with a Hackage revision?!

**Comment by rthomas** [comment]
Yeah it looks like @23Skidoo added that entry in there - are versions on Hackage mutable?

cabal-install-1.24.0.1 is now on Hackage also.

**Comment by rthomas** [comment]
Ok, Cabal 1.24.1.0 and cabal-install 1.24.0.1 are now up on Hackage and the downloads page, I'll leave this open for the time being to track the issue @sjakobi mentioned.

**Comment by rthomas** [comment]
Unfortunately it looks like I can't mutate the changelog in the release on Hackage, but I have pushed a commit to merge those two changelog lines in https://github.com/haskell/cabal/commit/360ba84218c2f1b5f61e6c88437ad534ca8ce620.

So I'll close this, please feel free to reopen if you're not happy with the solution.
