### ISSUE TITLE
cabal update uses too much bandwidth

### ISSUE THREAD

**Issue by bos** [haskell/cabal#421]
(Imported from [Trac #428](http://hackage.haskell.org/trac/hackage/ticket/428), reported by claus on 2008-12-05)

<tt>cabal update</tt> appears to download a compressed tarball (&gt;600k and growing), which is larger than most packages, takes a while over a slow line, and doesn't provide much info (<tt>-v</tt> just adds low-level details).

using <tt>rsync</tt> over the relevant parts of the directory tree ought to be faster (increasingly so as hackage keeps growing), use less bandwith, and be able to tell me which package descriptions have changed (although it would be nice to limit the latter info to new packages and changes to installed packages).

**Comment by BardurArantsson** [comment]
Given the plans of @dcoutts  (et al.) for index signing, incremental (secure!) update,etc. is any of this relevant any longer?

**Comment by ezyang** [comment]
This is fixed now due to Hackage Security!

**Comment by int-e** [comment]
@ezyang: This ticket is about incremental updating of the package database, and as far as I can see, that is still not implemented. (I just did a `cabal update` using cabal-install 2.0.0.0 (Cabal 2.0.0.2) and it downloaded the whole 60MB compressed `01-index.tar.gz` file rather than just the changes since the last update yesterday.)

What has improved is the situation when there are no changes at all; see #799.

**Comment by phadej** [comment]
@hvr, Seems that I have

```
-- This is the configuration file for the 'cabal' command line tool.
--
-- The available configuration options are listed below.
-- Some of them have default values listed.
--
-- Lines (like this one) beginning with '--' are comments.
-- Be careful with spaces and indentation because they are
-- used to indicate layout for nested sections.
--
-- This config file was generated using the following versions
-- of Cabal and cabal-install:
-- Cabal library version: 2.1.0.0
-- cabal-install version: 2.1.0.0


repository hackage.haskell.org
  url: http://hackage.haskell.org/
  -- secure: True
  -- root-keys:
  -- key-threshold: 3
```

why I don't have `secure: True` and root-keys? Did we miss something?

I guess that's why @int-e doesn't see incremental update

**Comment by int-e** [comment]
@phadej: Thanks for looking at this. I thought that `secure: True` is the default now; indeed with `secure: False` cabal-install is downloading the `00-index.tar.gz` file.

**Comment by int-e** [comment]
An underlying problem here *may* be that the `01-index.tar` file is not append-only; the last 1024 bytes seem to be a block of zeros that is overwritten when the archive is updated.

In any case this appears to be a hackage-security or possible hackage server issue, since these, in tandem, are supposed to provide incremental updates.

**Comment by int-e** [comment]
I just saw a successful incremental update. This is getting mysterious.

**Comment by int-e** [comment]
After some reflection I believe this was all my own fault. I messed with the `01-index.tar.gz` file, naively believing that it would be insane to incrementally download a gzipped file. But that's exactly what cabal-install does. The reason that otherwise the CDN would have to cache the whole uncompressed file the whole uncompressed file; cf. https://github.com/haskell/hackage-security/issues/104

(I'm not convinced that what it does, namely re-downloading the last 64kb of the existing file along with whatever is new, is sufficient, but I have no hard evidence that it ever goes wrong.)

Sorry for the noise.
