### ISSUE TITLE
`cabal new-haddock` doesn't generate docs for Backpack mixins

### ISSUE THREAD

**Issue by LightAndLight** [haskell/cabal#6035]
I don't know if this is a cabal issue or a haddock issue.

Modules that I generate via the `mixin` field in my .cabal don't have any docs generated for them. This is a big deal because I have a project in which many modules depend on a couple of signatures, so none of these modules have documentation generated. 

For an example, see https://github.com/LightAndLight/haddock-backpack-issue

**Comment by ezyang** [comment]
Related to https://github.com/haskell/haddock/issues/563 (which apparently I actually fixed in https://github.com/haskell/haddock/pull/547 ?!); basically, I suspect that we just need to apply the same treatment here to mixins.

**Comment by LightAndLight** [comment]
How might I make that happen? I've done a bit of reading through your PR, but I still don't understand the architecture very well.

When I run `cabal new-haddock` I get this message:
`Warning: Cannot find reexported module 'haddock-internal-libraries-0.1.0.0-inplace-internal-sig+7iiUI8z86EDBmHQqzyvgBz:C'`. I would imagine it should be generating docs for `haddock-internal-libraries-0.1.0.0-inplace-internal-sig+7iiUI8z86EDBmHQqzyvgBz[B.Sig=haddock-internal-libraries-0.1.0.0-inplace-internal-impl:B]:C`. Does that matter?

If I try to run `cabal new-haddock` and tell it to include the instantiated unit, it still says it can't find the module. What does it take for haddock to become aware of a module?

**Comment by LightAndLight** [comment]
Ping. I've been playing around with this a bit more. My previous comment is slightly wrong, but I think it points at the main issue- that fully instantiated indefinite modules have no docs generated. I've been reading through `Cabal` and `cabal-install` code, but I'm not sure whether this is a bug or intended behavior.

Here's a branch where the docs generation is even more broken, where I don't use the mixins field: https://github.com/LightAndLight/haddock-backpack-issue/tree/more-broken.

Would anyone be able to help me figure out how to fix this?

**Comment by 23Skidoo** [comment]
@ezyang is the one to talk to for everything Backpack-related.
