### ISSUE TITLE
cabal-install  3.6 on OSX doesn't handle ctrl-c (interrupts) correctly

### ISSUE THREAD

**Issue by cartazio** [haskell/cabal#8078]
**Describe the bug**
ctr+c should trigger a CLI application to start a clean shutdown process for the overall cli invocation, not for its many subtasks

**To Reproduce**

```
cabal install pandoc # on a machine with no build cache
# wait for it to be midway into downloading a dozen plus packages
ctrl+c
# see it just cancels stuff for just one sub task, not everything else
do control c again
# notice it just cancels another task
# start trying harder cmands that send more aggressive interrupts
```

Please use version-prefixed commands (e.g. `v2-build` or `v1-build`) to avoid ambiguity.

**Expected behavior**

ctrl c should start the shutdown of the build!
I think this used to work correctly?

**System information**
 - Operating system M1 pro OSX mac,
 - `cabal`, `ghc` versions ghc 9.2.2 ARM64, cabal 3.6

**Additional context**
i think what might be happening is that the sub computations register their own interrupt handles to the OS and somehow those are picked up? i cant im

**Comment by hasufell** [comment]
@robx is our process handling expert

**Comment by cartazio** [comment]
it might be a problem related to how downloads are managed (private chat with @hasufell ), but either way, its not an area of cabal i'm familiar with, and it hints at some sort of  serious architectural issues in how interrupts are registered and handled.

**Comment by hasufell** [comment]
Maybe it is already fixed https://github.com/haskell/cabal/pull/7929

**Comment by cartazio** [comment]
a secondary thing is doing ctrl z may not have actually stopped the child package jobs from building? (or i just dont understand control z)

**Comment by cartazio** [comment]
it would be nice if this was shipped in a bug fix release or something... its kinda important user facing behavior :) 

i'll poke at it more and see if master is better behaved..

**Comment by cartazio** [comment]
@jneira i'd be surprised if the bug didnt show up on other platforms

**Comment by robx** [comment]
Yeah this particular bug *should* be fixed in master.

Regarding Ctrl-C handling, what happens is
- the shell sends SIGINT to the whole process group (all children)
- Haskell's runtime by default converts SIGINT to a UserInterrupt async exception thrown at the main thread (or at least that's my working mental model)
- however, we spawn subprocesses using so called "Ctrl-C delegation", which means that we ignore SIGINT while a subprocess is running, and raise UserInterrupt when that subprocess exits due to the SIGINT it received

(compare https://hackage.haskell.org/package/process-1.6.13.2/docs/System-Process.html#g:4)

(I have no idea at this point of whether Ctrl-Z works reasonably.)

**Comment by jneira** [comment]
> @jneira i'd be surprised if the bug didnt show up on other platforms

yeah, it somewhat works in master thanks to #7929 and the main process is killed immediately but it lefts orphan subprocess as #7921 did not fix that for windows (but it did for other platforms afaik)

so maybe we could remove the tag and rename the issue to remove the macos mention

**Comment by robx** [comment]
I think as bug report, this is a duplicate of https://github.com/haskell/cabal/issues/6322.

**Comment by jneira** [comment]
oh yeah, good catch, @cartazio does that previous bug report represent yours enough to close this?

**Comment by cartazio** [comment]
yeah, sounds like the same bug, 
any remainder things that need an extra pair of eyes?

also is there any chance that there could be a bugfix release with this?

**Comment by jneira** [comment]
re processes there are another pending pr: https://github.com/haskell/cabal/pull/7757, maybe we could work on it
if you dont mind i am gonna close this one, feel free to comment here or in #6322
