### ISSUE TITLE
cabal 3.8.1.0 compiles temporary build path for datadir into alex, happy, other tools

### ISSUE THREAD

**Issue by essandess** [haskell/cabal#8482]
**Describe the bug**

I’m migrating several MacPorts Haskell builds from `stack` to `cabal` to get native `arm64` binaries linked to MacPorts libraries.

I observe that `cabal` version 3.8.1.0 compiles a temporary build path for `datadir` from `store-dir` into `alex`, `happy`, other binaries it compiles. This breaks projects for which `datadir` is required.

I’ve tried many different approaches to setting `datadir` To the correct, permanent location, but none of these methods work:
* `datadir: …` in the `config` file: https://github.com/macports/macports-ports/blob/69b89680a5f48245784b8376241f948bbd40a1c6/_resources/port1.0/group/haskell_cabal-1.0.tcl#L105
* `--datadir=…` in the command line
* `Paths_alex.hs` that specifies `datadir = …`
* Use the `--enable-relocatable` flag

Because these tools are necessary to bootstrap and use Haskell world, I’ve thrown in the towel and just used an ugly hack of replacing this incorrect path in the binary with the correct path padded with extraneous `/`‘s. See: https://github.com/macports/macports-ports/pull/16154

How can `cabal` compile a project like `alex` from source and set the correct `datadir`?

Likely related: #3586

**To Reproduce**

Compile `cabal build`/`install` of `alex`, `happy`, and so forth.

**System information**
 - macOS 12.6 21G115 x86_64
 - Xcode 14.0 14A309
 - `cabal` 3.8.1.0, `ghc` 9.4.2

**Additional context**
MacPorts build commands:
* https://github.com/macports/macports-ports/blob/master/devel/alex/Portfile
* https://github.com/macports/macports-ports/blob/master/_resources/port1.0/group/haskell_cabal-1.0.tcl

**Comment by gbaz** [comment]
The linked ticket cross-links to a large other number of related issues. I really do think we should tackle this for the next cabal release. The problem is I'm not sure what the right design to implement is! If someone wants to propose the exact semantics (perhaps with more flags) that cabal implement, this seems tractable and worthwhile.

**Comment by essandess** [comment]
> The linked ticket cross-links to a large other number of related issues. I really do think we should tackle this for the next cabal release. The problem is I'm not sure what the right design to implement is! If someone wants to propose the exact semantics (perhaps with more flags) that cabal implement, this seems tractable and worthwhile.

Thanks you—that would be much appreciated. I’ve discovered that the slash hack doesn’t work on `arm` architectures, and even this hack doesn’t provide a viable alternative on that platform. See https://github.com/macports/macports-ports/pull/16228.

**Comment by gbaz** [comment]
Based on the discussion there, could you just override this by setting $alex_datadir etc in the environment?

**Comment by gbaz** [comment]
I believe this is resolved by https://github.com/haskell/cabal/pull/8556

**Comment by Mikolaj** [comment]
Could anybody kindly verify using master branch (or cabal 3.10 when it gets released)? Let me close, but please open a new ticket if problems still occur.
