### ISSUE TITLE
Consider reverting default usage of `--enable-documentation` in cabal haddock

### ISSUE THREAD

**Issue by arybczak** [haskell/cabal#8725]
I was bitten by #8707 and I had no idea what was going on, had to search the issue tracker to find it.

Looks like now `cabal haddock` will with default settings (i.e. no `documentation: True` in the config file or `--disable-documentation` passed explicitly) lead to rebuild of all dependencies.

What is worse, if someone doesn't want to enable `documentation: True`, there seems to be no way to permanently disable this behavior.

I cannot emphasise enough how bad of a UX change this is.

Can this please be reverted?

**Comment by ulysses4ever** [comment]
As the author of the change in question, I'm happy with reverting, if people think that it's really annoying (and by the looks of it, they do).

**Comment by Mikolaj** [comment]
We've also had a lot of ticket from people bitten by the inverse default. Especially newcomers, and they need any help they can get. How can we resolve this in a better way? @arybczak: what would mollify you, for example?

**Comment by arybczak** [comment]
Well, for example having a way to disable this with a seting in `~/.cabal/config` would work.

The issue here is that the new behavior can't be disabled without passing `--disable-documentation` to `cabal haddock` every time you invoke it.

**Comment by mouse07410** [comment]
I'm not sure it would be good to revert - for example, I always build documentation (and have `documentation = True` in the global config).

**Comment by arybczak** [comment]
> for example, I always build documentation (and have documentation = True in the global config).

Great, then you're not affected by this change at all. Why would you be against the revert then?

**Comment by Bodigrim** [comment]
I find it extremely annoying to explain people, especially less experienced ones, that just `cabal haddock` is not enough and they must double down on their intention to build documentation with `cabal haddock --enable-documentation`. The sensible default behaviour is not to make users to ask you twice. Power users can always supply `--disable-documentation`.

**Comment by gbaz** [comment]
Agreed. I think this might be irritating the first time, but subsequently, as long as the versions don't change, then all those built haddocks will be cached and available, which on the whole will be handy. I'm certainly open to adding a global setting for controlling this as well though...

**Comment by andreasabel** [comment]
Does `documentation: False` in the `cabal.project` file work, @arybczak ?

**Comment by arybczak** [comment]
> Power users can always supply --disable-documentation.

No, power users should be able to disable this in the configuration file.

> might be irritating the first time, but subsequently, **as long as the versions don't change**

In reality they do almost every time you do `cabal update`.

> Does documentation: False in the cabal.project file work, @arybczak ?

It doesn't. That's the crux of a problem. There is currently no way to override this behavior (other than passing `--disable-documentation` on the command line **every single time**).

Again, the problem here is not that this change is bad, it's that **it's unconditionally enabled there is not way to disable it**.

I see two potential solutions:
- Enabling `documentation: True` by default and reverting #8259.
- Providing another `~/.cabal/config` option `haddock-documentation` with a default `True` that controls whether `--enable-documentation` is passed to `cabal haddock` so that it can be disabled.

**Comment by mouse07410** [comment]
A few naive questions.

1. Placing `documentation: False` in `cabal.project` should work, so, if it doesn't - it's probably a bug? And fixing it should resolve this issue?
2. Why would anybody invoke `cabal haddock`, if not for documentation? 
3. If a user does **not** want documentation in general - why not set `documentation: False` in `~/.cabal/config`, which presumably alleviates the problem?

**Comment by arybczak** [comment]
> Placing documentation: False in cabal.project should work, so, if it doesn't - it's probably a bug?

Perhaps. But why should it work for `cabal.project`, but not for `~/.cabal/config`?

> Why would anybody invoke cabal haddock, if not for documentation?

Did you try running `cabal haddock` without `--enable-documentation`? You still get the haddock for your package, but without links to external packages. For some people (like me) it's sufficient.

**Comment by gbaz** [comment]
My understanding of the global level "documentation: False" is that it is supposed to control whether or not haddocks are run on packages as they are built _in general_. It is not supposed to determine if we recursively generate documentation for sub-dependencies of an individual package where we have already opted into asking for docs.

Again though, I think having a global opt-out of this flag would be a good thing, and a welcome PR. However, given the arguments both ways, circling around reverting the existing change seems like it won't be very fruitful.

**Comment by arybczak** [comment]
> Again though, I think having a global opt-out of this flag would be a good thing, and a welcome PR.

Fair enough. I see there's a section `haddock` in the ~/.cabal/config, I'll make a PR that adds a `documentation` setting to this.

**Comment by Mikolaj** [comment]
@arybczak: thank you for the investigation. We are about to release, so let's gather here further feedback of this feature and ideas for improvements.

**Comment by vdukhovni** [comment]
FWIW, I strongly agree that the command-line override needs a configuration file equivalent.
As to whether dependency haddocks should be on by default, my inclination is to say "no".

**Comment by michaelpj** [comment]
I made another issue for the problem of possibly building the docs separately: https://github.com/haskell/cabal/issues/10111

**Comment by phadej** [comment]
Today I noticed that if you add a haddock flag, e.g. `--haddock-hoogle`, `cabal build` will rebuild all the transitive dependencies.

In past two years, I haven't found a situation where I liked `cabal haddock` (re)building the dependencies' docs by default. Please revert.

**Comment by arybczak** [comment]
Indeed. I'm still using build with a patch that reverts this locally:

```diff
diff --git a/cabal-install/src/Distribution/Client/CmdHaddock.hs b/cabal-install/src/Distribution/Client/CmdHaddock.hs
index 8ecc54877..666e9c178 100644
--- a/cabal-install/src/Distribution/Client/CmdHaddock.hs
+++ b/cabal-install/src/Distribution/Client/CmdHaddock.hs
@@ -34,7 +34,6 @@ import Distribution.Client.Setup
   ( CommonSetupFlags (..)
   , ConfigFlags (..)
   , GlobalFlags
-  , InstallFlags (..)
   )
 import Distribution.Client.TargetProblem
   ( TargetProblem (..)
@@ -149,9 +148,7 @@ haddockAction relFlags targetStrings globalFlags = do
 
   let
     verbosity = fromFlagOrDefault normal (setupVerbosity $ configCommonFlags configFlags)
-    installDoc = fromFlagOrDefault True (installDocumentation installFlags)
-    flags' = flags{installFlags = installFlags{installDocumentation = Flag installDoc}}
-    cliConfig = commandLineFlagsToProjectConfig globalFlags flags' mempty -- ClientInstallFlags, not needed here
+    cliConfig = commandLineFlagsToProjectConfig globalFlags flags mempty -- ClientInstallFlags, not needed here
   projCtx <- establishProjectBaseContext verbosity cliConfig HaddockCommand
 
   let relBaseCtx@ProjectBaseContext{projectConfig = relProjectConfig}
```

**Comment by ulysses4ever** [comment]
I'm looking at this now afresh. The discussion seems to have died out because of the dead-end with the more ambitious idea based on a new cabal option (so-called `full-documentation`). However, a simple idea seemed to have been overlooked in the back and forth: if people specify `documenation: False` in their config or project file, that should override the new default for `cabal haddock`. This looks like a very natural solution, which should also have a straightforward implementation. @arybczak will this make you switch back to un-patched cabal, at least?

**Comment by arybczak** [comment]
If this also works at the level of ~/.cabal/config, yes.
